"""create giveaway table

Revision ID: 46d61e685c2b
Revises: ccef2015d4be
Create Date: 2025-06-15 21:14:58.690998

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46d61e685c2b'
down_revision: Union[str, None] = 'ccef2015d4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaway',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hoster_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giveaway_participant',
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.PrimaryKeyConstraint('giveaway_id', 'discord_user_id')
    )
    op.create_table('giveaway_winner',
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.PrimaryKeyConstraint('giveaway_id', 'discord_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giveaway_winner')
    op.drop_table('giveaway_participant')
    op.drop_table('giveaway')
    # ### end Alembic commands ###
